parameters:
- name: manifest
  displayName: K8 Manifest
  type: string
  default: ./deploy/eshopweb-manifest.yaml
# Variable 'manifest' was defined in the Variables tab
trigger:
  branches:
    include:
    - feature-fmg
resources:
  repositories:
  - repository: self
    type: git
    ref: feature-fmg
jobs:
- job: Job_1
  displayName: Build Dotnet Code and Image
  pool:
    vmImage: ubuntu-20.04
  steps:
  - checkout: self
  - task: UseDotNet@2
    displayName: Use .NET Core sdk 3.1.x
    enabled: False
    inputs:
      version: 3.1.x
  - task: DotNetCoreCLI@2
    displayName: dotnet build
    enabled: False
    inputs:
      projects: ./eShopOnWeb.sln
  - task: DockerInstaller@0
    displayName: Install Docker 17.09.0-ce
    enabled: False
  - task: Docker@2
    displayName: buildAndPush
    enabled: False
    inputs:
      containerRegistry: 1e8b919a-2b7c-4f3b-bd2d-43cadf512093
      repository: mhildenb/eshopweb
      Dockerfile: ./src/Web/Dockerfile
      buildContext: .
  - task: oc-setup@2
    displayName: 'oc-setup '
    enabled: False
    inputs:
      openshiftService: 27f93aa4-72d3-421a-b97c-623b779e29ca
  - task: Bash@3
    displayName: Bash Script
    enabled: False
    inputs:
      filePath: deploy/deploy.sh
      arguments: $(Build.BuildId)
  - task: CopyFiles@2
    displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
    inputs:
      SourceFolder: deploy
      TargetFolder: $(build.artifactstagingdirectory)
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
  - task: KubernetesManifest@0
    displayName: deploy
    inputs:
      kubernetesServiceConnection: ddc46a55-5e29-40f8-9731-f0612aeb1abc
      namespace: az-demo-stage
      manifests: $(manifest)
      containers: quay.io/mhildenb/eshopweb:365

