parameters:
- name: manifest
  displayName: K8 Manifest
  type: string
  default: ./deploy/eshopweb-manifest.yaml

trigger:
  branches:
    include:
    - feature-fmg

resources:
  repositories:
  - repository: self
    type: git
    ref: feature-fmg

jobs:
- job: Job_1
  displayName: Build Dotnet Code and Image
  pool:
    vmImage: ubuntu-20.04
  steps:
  - checkout: self

  # do this before all your .NET Core tasks
  - task: UseDotNet@2
    displayName: Use .NET Core sdk 3.1.x
    enabled: False
    inputs:
      version: 3.1.x
  - task: DotNetCoreCLI@2
    displayName: dotnet build
    enabled: False
    inputs:
      projects: ./src/Web/Web.csproj

  - task: DockerInstaller@0
    displayName: Install Docker 17.09.0-ce
  - task: Docker@2
    displayName: buildAndPush
    inputs:
      containerRegistry: 1e8b919a-2b7c-4f3b-bd2d-43cadf512093
      repository: mhildenb/eshopweb
      Dockerfile: ./src/Web/Dockerfile
      buildContext: .

  - task: oc-setup@2
    displayName: 'oc-setup '
    inputs:
      openshiftService: 27f93aa4-72d3-421a-b97c-623b779e29ca

  - task: Bash@3
    displayName: Bash Script
    inputs:
      filePath: deploy/deploy.sh
      arguments: $(Build.BuildId)

  - task: CopyFiles@2
    displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
    inputs:
      SourceFolder: deploy
      TargetFolder: $(build.artifactstagingdirectory)
      
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'